# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiterm < Formula
  desc ""
  homepage "https://aiterm.net"
  version "0.1.0"

  on_macos do
    url "https://github.com/awgst/aiterm/releases/download/v0.1.0/aiterm_0.1.0_darwin_all.tar.gz"
    sha256 "7222c09f77c206ea5d24ca296850301431083b07a4593ed4cd0f844fd73bbece"

    def install
      bin.install "aiterm"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awgst/aiterm/releases/download/v0.1.0/aiterm_0.1.0_linux_arm64.tar.gz"
      sha256 "1ea849772f81d1f2f5ed18ac0da5618851d1af36b04de781aa72dd9e03a59250"

      def install
        bin.install "aiterm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awgst/aiterm/releases/download/v0.1.0/aiterm_0.1.0_linux_amd64.tar.gz"
      sha256 "50198816f65cb184d2dbb66dd48f96abb03eaa60f5084cd978a8baaaa948070a"

      def install
        bin.install "aiterm"
      end
    end
  end
end
