# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiterm < Formula
  desc ""
  homepage "https://aiterm.net"
  version "0.5.0"

  on_macos do
    url "https://raw.githubusercontent.com/awgst/aiterm-releases/main/aiterm_0.5.0_darwin_all.tar.gz"
    sha256 "0415ba32299bab92eb20f285051bd6b357e5ade507fbf530a4d7640c1f374c04"

    def install
      bin.install "aiterm"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://raw.githubusercontent.com/awgst/aiterm-releases/main/aiterm_0.5.0_linux_amd64.tar.gz"
      sha256 "e03e67326bf4802b7a3d027e4af44b10a3e3863deb3f08b2e87a882ae83b076a"

      def install
        bin.install "aiterm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://raw.githubusercontent.com/awgst/aiterm-releases/main/aiterm_0.5.0_linux_arm64.tar.gz"
      sha256 "e16d869818bd9b0c8a81af512ac5d076d8f803e91e0205bb5a17aa157882d6bf"

      def install
        bin.install "aiterm"
      end
    end
  end
end
