# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiterm < Formula
  desc ""
  homepage "https://aiterm.net"
  version "0.6.1"

  on_macos do
    url "https://github.com/awgst/aiterm/releases/download/v0.6.1/aiterm_0.6.1_darwin_all.tar.gz"
    sha256 "7c6f1e6be06e2d08ba7b131a7c8da4804e6c485a40969589ba822ad356e6b9dc"

    def install
      bin.install "aiterm"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/awgst/aiterm/releases/download/v0.6.1/aiterm_0.6.1_linux_arm64.tar.gz"
      sha256 "91f0164f10a89b93edc25915e6d6450735d77c07accd41ec119d68e422708833"

      def install
        bin.install "aiterm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/awgst/aiterm/releases/download/v0.6.1/aiterm_0.6.1_linux_amd64.tar.gz"
      sha256 "cad991834c8619fa39611a11ea61eb21f352f77cbaec8b759d7982c7d84d638d"

      def install
        bin.install "aiterm"
      end
    end
  end
end
